site_name: mbed Release Documents

docs_dir: Docs

pages:
- ['index.md','mbed Release Documents']
- ['5_1/release.md', '5.1', 'mbed OS release note']
- ['5_1/known.md', '5.1', 'mbed OS known issues list']
