site_name: mbed OS Release Documents

docs_dir: Docs

pages:
- ['index.md','mbed OS Release Documents']
- ['5_1/release.md', '5.1', 'mbed OS release note']

copyright: © ARM Ltd. Copyright 2016 – ARM mbed IoT Device Platform
